services:
  api:
    build:
      target: dev
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app/src
    command: npx nodemon --legacy-watch src/server.js

  mongo:
    ports:
      - "127.0.0.1:27017:27017"
